genomeDir: "resources/genome"
fasta: "resources/genome/genome.fa"
gtf: "resources/genome/genes.gtf"

samples:
    - Day0.Naive_L1Pf7
    - Day0.Naive_L1Pf7
    - Day2.GFP_L1Pf2
    - Day2.GFP_L1Pf2
    - Day2.NoGFP_L1Pf1
    - Day2.NoGFP_L1Pf1
    - Day4.GFP_L1Pf4
    - Day4.GFP_L1Pf4
    - Day4.NoGFP_L1Pf3
    - Day4.NoGFP_L1Pf3
    - Day6.GFP_L1Pf6
    - Day6.GFP_L1Pf6
    - Day6.NoGFP_L1Pf5
    - Day6.NoGFP_L1Pf5
    - L1Pf9_S13
    - L1Pf9_S13
    - L1PfM1_S13
    - L1PfM1_S13
    - L1PfM2_S14
    - L1PfM2_S14
    - L2Pf1_S1
    - L2Pf1_S1
    - L2Pf2_S2
    - L2Pf2_S2
    - L2Pf3_S3
    - L2Pf3_S3
    - L2Pf4_S4
    - L2Pf4_S4
    - L2Pf5_S5
    - L2Pf5_S5
    - L2Pf5_S7
    - L2Pf5_S7
    - L2Pf6_S6
    - L2Pf6_S6
    - L2Pf6_S8
    - L2Pf6_S8
    - L3Pf1_S1
    - L3Pf1_S1
    - L3Pf1_S7
    - L3Pf1_S7
    - L3Pf2_S2
    - L3Pf2_S2
    - L3Pf2_S8
    - L3Pf2_S8
    - L3Pf2Mix_S3
    - L3Pf2Mix_S3
    - L3Pf3_S4
    - L3Pf3_S4
    - L3Pf3_S9
    - L3Pf3_S9
    - L3Pf4_S10
    - L3Pf4_S10
    - L3Pf4_S5
    - L3Pf4_S5
    - L3Pf4Mix_S6
    - L3Pf4Mix_S6
    - L3Pf5_S11
    - L3Pf5_S11
    - L3Pf5_S9
    - L3Pf5_S9
    - L3Pf6_S10
    - L3Pf6_S10
    - L3Pf6_S12
    - L3Pf6_S12
    - L3Pf7_S11
    - L3Pf7_S11
    - L3Pf8_S12
    - L3Pf8_S12
    - SPZ_L1Pf8
    - SPZ_L1Pf8
    - TR2_L1Pf2_S1
    - TR2_L1Pf2_S1
    - TR2_L1Pf3_S2
    - TR2_L1Pf3_S2
    - TR2_L1Pf4_S3
    - TR2_L1Pf4_S3
    - TR2_L1Pf5_S4
    - TR2_L1Pf5_S4
    - TR2_L1Pf6_S5
    - TR2_L1Pf6_S5
    - TR2_L2Pf1_S6
    - TR2_L2Pf1_S6
    - TR2_L2Pf2_S7
    - TR2_L2Pf2_S7
    - TR2_L2Pf3_S8
    - TR2_L2Pf3_S8
    - TR2_L2Pf4_S9
    - TR2_L2Pf4_S9
    - TR2_L2Pf5_S10
    - TR2_L2Pf5_S10
    - TR2_L2Pf6_S11
    - TR2_L2Pf6_S11
